// src/components/entries/entry/fields/Matrix.vue
<template>
    <div>
        <div
            class="tw-border tw-rounded-md tw-p-4 t-pt-2 tw-relative"
            :class="{
                'tw-border-neutral-400': $vuetify.theme.name === 'light',
                'tw-border-neutral-500': $vuetify.theme.name === 'dark'
            }"
        >
            <h2 class="tw-text-lg tw-mb-6">{{ config.label[$i18n.locale]}}</h2>

            <template v-if="isReady">
                <template v-if="arrayValue.length === 0">
                    <div class="tw-flex tw-flex-col tw-items-center tw-gap-y-4">
                        <h3
                            class="tw-text-center tw-text-xl"
                            :class="{
                            'tw-text-neutral-400': $vuetify.theme.name === 'light',
                            'tw-text-neutral-500': $vuetify.theme.name === 'dark'
                        }"
                        >
                            {{ $t('system.no_items_now') }}
                        </h3>
                        <v-btn @click.prevent="addElement" variant="text" color="primary">{{ $t('system.add_item') }}</v-btn>
                    </div>
                </template>

                <template v-else>
                    <div :id="id" class="tw-flex tw-flex-col tw-gap-y-4">
                        <template v-for="(group, idx) in arrayValue" :key="'group_' + idx + '_' + index">
                            <div class="tw-rounded-md tw-p-4" :class="{'tw-bg-zinc-800': $vuetify.theme.name === 'dark', 'tw-bg-gray-100': $vuetify.theme.name === 'light'}">
                                <div class="tw-flex tw-flex-row tw-mb-4 tw-justify-between tw-items-center">
                                    <div class="tw-flex tw-flex-row tw-gap-x-2 list-dnd-handle">
                                        <v-icon icon="mdi-menu" class="tw-cursor-grab"/><h3 class="tw-font-medium">{{ $t('system.group') }} #{{ idx+1 }}</h3>
                                    </div>
                                    <div>
                                        <v-btn @click.prevent="(e) => arrayValue.splice(idx, 1)" class="!tw-h-[30px]" variant="tonal" density="compact" color="red"><v-icon icon="mdi-trash-can-outline" /></v-btn>
                                    </div>
                                </div>

                                <div class="tw-flex tw-flex-col tw-gap-y-4">
                                    <template v-for="(_field, idxx) in fieldData" :key="'matrix_field_' + '_' + idx + '_' + index + '_' + idxx">
                                        <component
                                            :is="AvailableFields[_field.type].component"
                                            :type="AvailableFields[_field.type].type"
                                            v-model="arrayValue[idx][_field.key]"
                                            :config="_field"
                                            :index="idx"
                                            :locale="entry.locale"
                                        />
                                    </template>
                                </div>
                            </div>
                        </template>
                    </div>
                    <v-btn @click.prevent="addElement" variant="flat" color="primary" class="tw-absolute tw-top-4 tw-right-4">{{ $t('system.add') }}</v-btn>
                </template>
            </template>
            <template v-else>
                <div class="tw-h-[140px] tw-w-6/12 tw-flex tw-flex-col tw-items-center tw-justify-center tw-mx-auto">
                    <v-progress-linear :indeterminate="true" color="primary" :height="7" class="tw-rounded-md"/>
                </div>
            </template>
        </div>
    </div>
</template>

<script setup>
import { useI18n } from 'vue-i18n';
import { nextTick, onMounted, ref, watch } from 'vue';
import { Entries } from '@/libs/graphql/lib/entries';
import { SailCMS } from '@/libs/graphql';
import { AvailableFields } from '@/components/entries/entry/fields/Fields';
import { entry } from '@/components/entries/entry/entry';
import Sortable from 'sortablejs';
import { v4 } from 'uuid';
import { arrayMoveImmutable } from 'array-move';

const i18n = useI18n();
const id = ref('matrix_' + v4());

const props = defineProps({
    modelValue: {
        default: null
    },
    config: {
        type: Object,
        default: {type: '', label: '', name: '', validation: '', required: false, repeatable: false, config: null, width: 'full'}
    },
    type: {
        type: String,
        default: 'text'
    },
    index: {
        type: Number,
        default: 0
    }
});

const emitter = defineEmits(['update:modelValue']);
const arrayValue = ref(props.modelValue || []);
const isReady = ref(false);
const fieldData = ref([]);
const dndEstablished = ref(false);

// Add element to array
const addElement = () =>
{
    let struct = {};
    for (let field of fieldData.value) {
        struct[field.key] = '';
    }

    arrayValue.value.push(struct);

    nextTick(() =>
    {
        if (!dndEstablished.value) {
            const el = document.querySelector('#' + id.value);

            if (el) {
                new Sortable(
                    el,
                    {
                        tag: 'div',
                        direction: 'vertical',
                        ghostClass: 'ghost',
                        handle: '.list-dnd-handle',
                        animation: 300,
                        swapTreshold: 0.05,
                        dragoverBubble: false,
                        onEnd: sortingChange
                    }
                );

                dndEstablished.value = true;
            }
        }
    });
}

function moveElement(array, fromIndex, toIndex)
{
    const element = array.splice(fromIndex, 1)[0];
    array.splice(toIndex, 0, element);
    return array;
}

const sortingChange = (e) =>
{
    let oldIndex = e.oldIndex;
    let newIndex = e.newIndex;

    if (e.type === 'end') {
        arrayValue.value = arrayMoveImmutable(arrayValue.value, oldIndex, newIndex);
    }
}

// Report back any changes to the array
watch(arrayValue, (v) => emitter('update:modelValue', arrayValue), {deep: true});

const loadInfo = async () =>
{
    fieldData.value = await Entries.fieldsForMatrix(props.config._id, SailCMS.getLocales());
    isReady.value = true;
}

// Fetch Field Info for matrix
loadInfo();
</script>

<style>
.ghost {
    opacity: 0.45;
}
</style>

// src/components/fieldtypes/matrix.svelte
<script>
    import { _ } from 'svelte-i18n';
    import { Entries } from '@graphql/lib/entries.js';
    import { SailCMS } from '@graphql/index.js';
    import { Icon } from '@steeze-ui/svelte-icon';
    import { Menu, Trash } from '@steeze-ui/lucide-icons';
    import Sortable from 'sortablejs';
    import Searchable from '@components/utils/searchable.svelte';

    export let config = {fields: []};
    export let type = 'matrix';

    let internalValue = {fields: config.fields || []};
    let sortable = null;
    let selector = null;
    let isReady = false;
    let fieldList = [];
    let selectedField = null;

    const addField = () =>
    {
        internalValue.fields = [...internalValue.fields, selectedField];
        config = internalValue;
        selectedField = null;
        selector.clear();
    }

    const deleteField = (id) =>
    {
        let idx = internalValue.fields.findIndex(f => f === id);

        if (idx >= 0) {
            for (let field of fieldList) {
                if (field._id === id) {
                    field.used = false;
                }
            }

            internalValue.fields = internalValue.fields.filter((f, indx) => indx !== idx);
            config = internalValue;
            selector.updateFields(fieldList);
        }
    }

    const handleChange = () =>
    {
        let elms = document.getElementsByClassName('choice-item');
        let choices = [];

        for (let el of elms) {
            let id = el.getAttribute('data-id');
            let item = fieldList.find(f => f._id === id);
            choices = [...choices, item._id];
        }

        // Note: We do not update the internalValue here because it causes it reset the first time you move an item
        // This sets the right value at the top level and triggers all changes. The order of internalValue does not
        // matter at this point since the drag and drop library will tell us the order on every change.
        config.fields = choices;
    }

    const handleSelect = (e) =>
    {
        selectedField = e.detail

        for (let field of fieldList) {
            if (field._id === e.detail) {
                field.used = true;
            }
        }
    }

    const getField = (field) => fieldList.find(f => field === f._id);

    const init = async () =>
    {
        fieldList = await Entries.fields(SailCMS.getLocales());

        setTimeout(() => isReady = true, 25);

        const opts = {
            tag: 'div',
            direction: 'vertical',
            handle: '.list-dnd-handle',
            ghostClass: 'ghost',
            animation: 0,
            swapTreshold: 0.05,
            dragoverBubble: false,
            onEnd: handleChange
        };

        setTimeout(() =>
        {
            let el = document.querySelector('#choice-wrapper');
            sortable = new Sortable(el, opts);
        }, 50);
    }

    init();
</script>

{#if isReady}
    <div class="grid grid-cols-2 gap-y-6">
        <div class="w-full flex flex-row gap-x-4 items-center">
            <div class="flex-grow"><Searchable bind:this={selector} placeholder={$_('fields.options.add_field_ph')} showSelection={true} fields={fieldList} on:selected={handleSelect} /></div>
            <button on:click={addField} class="btn variant-filled-primary !py-[0.35rem]">{$_('system.add')}</button>
        </div>
        <div></div>

        <div id="choice-wrapper" class="choice-wrapper">
            {#each internalValue.fields as field, idx}
                {@const f = getField(field)}
                <div class="choice-item group" data-id={f._id}>
                    <div class="flex flex-row gap-x-4 items-center">
                        <div class="cursor-grab list-dnd-handle">
                            <Icon src={Menu} size="24"/>
                        </div>
                        <span>{f.name}</span>
                    </div>
                    <div class="flex-col items-center hidden group-hover:flex">
                        <button on:click={() => deleteField(f._id)} class="hover:text-red-500">
                            <Icon src={Trash} size="20" />
                        </button>
                    </div>
                </div>
            {:else}
                <h2 class="text-center text-lg text-surface-400 dark:text-surface-400">{$_('fields.options.no_fields')}</h2>
            {/each}
        </div>
    </div>
{/if}

<style lang="scss">
    .choice-wrapper {
        @apply border border-surface-300 dark:border-surface-400 p-4 rounded-md flex flex-col gap-y-4;
    }

    .choice-item {
        @apply flex flex-row justify-between items-center border border-surface-300;
        @apply dark:border-surface-400 p-4 hover:border-surface-500 dark:hover:border-surface-200;
        @apply dark:bg-surface-700;
    }

    .ghost {
        opacity: 0.55;
    }
</style>
