// src/components/entries/fields/types/Select.vue
<template>
    <div class="tw-w-full tw-grid tw-grid-cols-1 md:tw-grid-cols-2 tw-gap-y-4 tw-gap-x-6 tw-mt-4">
        <div class="tw-w-full tw-col-span-2">
            <h2 class="tw-mb-3">Add choice</h2>
            <div class="tw-flex tw-flex-col md:tw-flex-row tw-items-start tw-w-full md:tw-w-8/12 lg:tw-w-7/12 xl:tw-w-6/12 tw-gap-x-6">
                <v-text-field
                    variant="outlined"
                    color="primary"
                    hide-details
                    density="comfortable"
                    :label="$t('fields.options.value')"
                    v-model="value"
                    class="tw-w-4/12"
                />
                <v-text-field
                    variant="outlined"
                    color="primary"
                    hide-details
                    density="comfortable"
                    :label="$t('fields.options.select_label')"
                    v-model="label"
                    class="tw-w-4/12"
                />
                <div class="tw-flex-grow tw-w-4/12">
                    <v-btn @click.prevent="addChoice" variant="flat" color="primary" class="tw-mt-1.5">Add Choice</v-btn>
                </div>
            </div>

            <div
                class="tw-border tw-p-4 tw-mt-6 tw-mb-2 tw-w-full md:tw-w-8/12 lg:tw-w-7/12 xl:tw-w-6/12 tw-rounded-md"
                :class="{'tw-border-black/30': $vuetify.theme.name === 'light', 'tw-border-white/30': $vuetify.theme.name === 'dark'}"
            >
                <h3 v-if="internalValue.choices.length === 0" class="tw-text-center tw-font-medium">No Choices yet.</h3>

                <div v-else id="sortable-choices" class="tw-flex tw-flex-col tw-gap-y-2">
                    <div
                        v-for="choice in internalValue.choices"
                        :id="choice.value"
                        class="tw-px-4 tw-py-2 tw-group tw-rounded-md tw-flex tw-flex-row tw-items-center tw-justify-between"
                        :class="{'hover:tw-bg-neutral-800 tw-border tw-border-white/30': $vuetify.theme.name === 'dark', 'hover:tw-bg-gray-300 tw-border tw-border-black/30': $vuetify.theme.name === 'light'}"
                    >
                        <div>
                            <v-icon icon="mdi-menu" class="list-dnd-handle tw-mr-1 tw-cursor-grab"/>
                            {{ choice.value }} : {{ choice.title }}
                        </div>
                        <a href="" class="hover:tw-text-red-500 tw-invisible group-hover:tw-visible">
                            <v-icon icon="mdi-trash-can-outline" size="small"/>
                        </a>
                    </div>
                </div>
            </div>
        </div>

        <div class="tw-col-span-2 tw-mt-[-10px]">
            <div class="tw-flex tw-flex-row tw-gap-x-6">
                <v-switch
                    v-model="internalValue.multi"
                    :label="$t('fields.options.multi')"
                    color="primary"
                    value="1"
                    hide-details
                    class="tw-flex-grow"
                />
            </div>
        </div>
    </div>
</template>

<script setup>
import { watch, ref, onMounted, nextTick } from 'vue';
import { cloneDeep } from 'lodash';
import { useI18n } from 'vue-i18n';
import Sortable from 'sortablejs';

const i18n = useI18n();

const rules = {
    required: value => !!value || i18n.t('user.errors.required'),
};

const props = defineProps({
    field: {
        type: Object,
        default: {}
    },
    type: {
        type: Object,
        default: {}
    }
});

const addChoice = () =>
{
    internalValue.value.choices.push({value: value.value, title: label.value});
    value.value = '';
    label.value = '';
}

const handleChange = (e) =>
{
    let choices = [];
    let children = Array.from(document.querySelector('#sortable-choices').children);

    for (let child of children) {
        const item = internalValue.value.choices.find(i => i.value === child.id);

        if (item) {
            choices.push(item);
        }
    }

    choiceList = choices;
    const config = cloneDeep(props.field.config);
    config.choices = choices;
    config.multi = internalValue.value.multi;
    emitter('change', config);
}

const emitter = defineEmits(['change']);
const internalValue = ref({choices: props.field.config.choices || [], multi: props.field.config.multi || false});
let choiceList = [];

let sortable = null;
const label = ref('');
const value = ref('');
const sortableCreated = ref(false);

const opts = {
    tag: 'div',
    direction: 'vertical',
    handle: '.list-dnd-handle',
    ghostClass: 'ghost',
    animation: 0,
    swapTreshold: 0.05,
    dragoverBubble: false,
    onEnd: handleChange
};

watch(internalValue.value, (v) =>
{
    const config = cloneDeep(props.field.config);
    config.choices = choiceList;
    config.multi = v.multi;
    emitter('change', config);

    nextTick(() =>
    {
        if (config.choices.length > 0 && !sortableCreated.value) {
            sortableCreated.value = true;
            let el = document.querySelector('#sortable-choices');
            sortable = new Sortable(el, opts);
        }
    });
});

onMounted(() =>
{
    if (internalValue.value.choices.length > 0) {
        sortableCreated.value = true;
        let el = document.querySelector('#sortable-choices');
        sortable = new Sortable(el, opts);
    }
});
</script>

<style>
.ghost {
    opacity: 0.5;
}
</style>

// src/components/fieldtypes/select.svelte
<script>
    import { _ } from 'svelte-i18n';
    import { Icon } from '@steeze-ui/svelte-icon';
    import { AlertTriangle, Menu, Trash } from '@steeze-ui/lucide-icons';
    import TextInput from '@components/forms/textinput.svelte';
    import Sortable from 'sortablejs';
    import { onMount } from 'svelte';
    import { SlideToggle } from '@skeletonlabs/skeleton';

    export let config = {choices: [], multi: false};
    export let type = 'select';

    let internalValue = {choices: config.choices || [], multi: config.multi || false};

    let label = '';
    let value = '';
    let showError = false;
    let sortable;

    const addChoice = () =>
    {
        let foundValue = internalValue.choices.find(c => c.value === value);

        if (foundValue) {
            showError = true;
            return;
        }

        internalValue.choices = [...internalValue.choices, {value: value, label: label}];
        config.choices = internalValue.choices;

        value = '';
        label = '';
    }

    const deleteChoice = (idx) =>
    {
        internalValue.choices = internalValue.choices.filter((c, ind) => ind !== idx);
        config.choices = internalValue.choices;
    }

    const handleChange = (e) =>
    {

        let elms = document.getElementsByClassName('choice-item');
        let choices = [];

        for (let el of elms) {
            let value = el.getAttribute('data-value');
            let item = internalValue.choices.find(c => c.value === value);
            choices = [...choices, item];
        }

        // Note: We do not update the internalValue here because it causes it reset the first time you move an item
        // This sets the right value at the top level and triggers all changes. The order of internalValue does not
        // matter at this point since the drag and drop library will tell us the order on every change.
        config.choices = choices;
    }

    const updateMulti = (e) => config = internalValue;

    onMount(() =>
    {
        const opts = {
            tag: 'div',
            direction: 'vertical',
            handle: '.list-dnd-handle',
            ghostClass: 'ghost',
            animation: 0,
            swapTreshold: 0.05,
            dragoverBubble: false,
            onEnd: handleChange
        };

        let el = document.querySelector('#choice-wrapper');
        sortable = new Sortable(el, opts);
    });
</script>

<div class="grid grid-cols-2 gap-y-6">
    <div class="w-full flex flex-row gap-x-4 items-center">
        <TextInput type="text" blockClass="flex-grow" bind:value={value} validation={['required']} placeholder={$_('fields.options.value')} />
        <TextInput type="text" blockClass="flex-grow" bind:value={label} validation={['required']} placeholder={$_('fields.options.select_label')} />

        <button on:click={addChoice} class="btn variant-filled-primary">{$_('system.add')}</button>
    </div>
    <div></div>

    {#if showError}
        <div class="col-span-1 alert variant-ghost-error">
            <div class="text-red-300">
                <Icon src={AlertTriangle} size="24"/>
            </div>
            <div class="alert-message text-red-300">
                <p>{$_('fields.value_exists')}.</p>
            </div>
        </div>
        <div></div>
    {/if}

    <div id="choice-wrapper" class="choice-wrapper">
        {#each internalValue.choices as choice, idx}
            <div class="choice-item group" data-value={choice.value}>
                <div class="flex flex-row gap-x-4 items-center">
                    <div class="cursor-grab list-dnd-handle">
                        <Icon src={Menu} size="24"/>
                    </div>
                    <span>{choice.value} &mdash; {choice.label}</span>
                </div>
                <div class="flex-col items-center hidden group-hover:flex">
                    <button on:click={() => deleteChoice(idx)} class="hover:text-red-500">
                        <Icon src={Trash} size="20" />
                    </button>
                </div>
            </div>
        {:else}
            <h2 class="text-center text-lg text-surface-400 dark:text-surface-400">{$_('fields.options.no_choices')}</h2>
        {/each}
    </div>
    <div></div>

    <div>
        <SlideToggle
            name="slider-label"
            background="bg-surface-200 dark:bg-surface-400"
            active="bg-primary-500"
            bind:checked={internalValue.multi}
            on:change={updateMulti}
        >
            {$_('fields.options.multi')}
        </SlideToggle>
    </div>
</div>

<style lang="scss">
    .choice-wrapper {
        @apply border border-surface-300 dark:border-surface-400 p-4 rounded-md flex flex-col gap-y-4;
    }

    .choice-item {
        @apply flex flex-row justify-between items-center border border-surface-300;
        @apply dark:border-surface-400 p-4 hover:border-surface-500 dark:hover:border-surface-200;
        @apply dark:bg-surface-700;
    }

    .ghost {
        opacity: 0.55;
    }
</style>
