// src/components/entries/fields/types/Textarea.vue
<template>
    <div class="tw-w-full tw-grid tw-grid-cols-1 md:tw-grid-cols-2 tw-gap-y-4 tw-gap-x-6 tw-mt-4">
        <v-text-field
            type="number"
            variant="outlined"
            color="primary"
            density="comfortable"
            :rules="[rules.required]"
            :label="$t('fields.options.rows') + ' *'"
            v-model="internalValue.rows"
        />

        <v-text-field
            type="number"
            variant="outlined"
            color="primary"
            density="comfortable"
            :rules="[rules.required]"
            :label="$t('fields.options.max_chars') + ' *'"
            v-model="internalValue.max"
        >
            <template v-slot:details><span class="tw-mr-[-12px]" :class="{'tw-text-white/40': $vuetify.theme.name === 'dark', 'tw-text-black/60': $vuetify.theme.name === 'light'}">{{ $t('fields.options.max_chars_explain') }}</span></template>
        </v-text-field>
    </div>
</template>

<script setup>
import { watch, ref } from 'vue';
import { cloneDeep } from 'lodash';
import { useI18n } from 'vue-i18n';

const i18n = useI18n();

const rules = {
    required: value => !!value || i18n.t('user.errors.required'),
};

const props = defineProps({
    field: {
        type: Object,
        default: {}
    },
    type: {
        type: Object,
        default: {}
    }
});

const emitter = defineEmits(['change']);

const internalValue = ref({rows: props.field.config.rows || 8, max: props.field.config.max_chars || -1});

watch(internalValue.value, (v) =>
{
    const config = cloneDeep(props.field.config);
    config.rows = parseInt(v.rows);
    config.max_chars = parseInt(v.max);
    emitter('change', config);
});
</script>

// src/components/fieldtypes/textarea.svelte
<script>
    import { _ } from 'svelte-i18n';

    export let config = {rows: 8, max: -1};
    export let type = 'textarea';

    let internalValue = {rows: config.rows || 8, max: config.max || -1};

    $: {
        config = internalValue;
    }
</script>

<div class="grid grid-cols-2 gap-4">
    <div>
        <label>{$_('fields.options.rows')}:</label>
        <input type="number" class="input" bind:value={internalValue.rows}/>
    </div>

    <div>
        <label>{$_('fields.options.max_chars')}:</label>
        <input type="number" class="input" bind:value={internalValue.max}/>
        <small class="text-right block">{$_('fields.options.max_chars_explain')}</small>
    </div>
</div>
