// src/components/fieldtypes/entry.svelte
<script>
    import { _ } from 'svelte-i18n';
    import { Entries } from '@graphql/lib/entries.js';
    import { SailCMS } from '@graphql/index.js';
    import { SlideToggle } from '@skeletonlabs/skeleton';

    export let config = {type: 'page', multi: false};
    export let type = 'entry';

    let isReady = false;
    let internalValue = {type: config.type || 'page', multi: config.type || false};
    let entryTypes = [];

    const handleSelect = () => config = internalValue;
    const updateMulti = () => config = internalValue;

    const init = async () =>
    {
        const types = await Entries.entryTypes(SailCMS.getLocales());

        for (let type of types) {
            entryTypes = [...entryTypes, {value: type.handle, label: type.title}];
        }

        isReady = true;
    }

    init();
</script>

<div class="grid grid-cols-1 gap-y-6">
    {#if isReady}
        <div>
            <label>{$_('fields.options.entry_type')} <span class="text-red-500">*</span>:</label>
            <select bind:value={internalValue.type} on:change={handleSelect} class="select !bg-white dark:!bg-surface-600 dark:!border-surface-900 !rounded-md">
                {#each entryTypes as type}
                    <option value={type.value}>{$_(type.label)}</option>
                {/each}
            </select>
        </div>

        <div>
            <SlideToggle
                    name="slider-label"
                    background="bg-surface-200 dark:bg-surface-400"
                    active="bg-primary-500"
                    bind:checked={internalValue.multi}
                    on:change={updateMulti}
            >
                {$_('fields.options.multi')}
            </SlideToggle>
        </div>
    {/if}
</div>

// src/components/entries/fields/types/Entry.vue
<template>
    <div class="tw-w-full tw-grid tw-grid-cols-1 md:tw-grid-cols-2 tw-gap-y-4 tw-gap-x-6 tw-mt-4">
        <v-select
            :items="entryTypes"
            :model-value="internalValue.type"
            id="type-selector"
            :label="$t('fields.options.entry_type') + ' *'"
            color="primary"
            variant="outlined"
            density="comfortable"
            :placeholder="$t('fields.options.country')"
            :rules="[rules.required]"
            :persistent-hint="false"
            class="tw-col-span-2"
        ></v-select>

        <div class="tw-col-span-2 tw-mt-[-10px]">
            <div class="tw-flex tw-flex-row tw-gap-x-6">
                <v-switch
                    v-model="internalValue.multi"
                    :label="$t('fields.options.multi')"
                    color="primary"
                    value="1"
                    hide-details
                    class="tw-flex-grow"
                />
            </div>
        </div>
    </div>
</template>

<script setup>
import { watch, ref, computed } from 'vue';
import { cloneDeep } from 'lodash';
import { useI18n } from 'vue-i18n';
import { Countries } from '@/libs/countries';
import { Entries } from '@/libs/graphql/lib/entries';
import { SailCMS } from '@/libs/graphql';

const i18n = useI18n();

const rules = {
    required: value => !!value || i18n.t('user.errors.required'),
};

const props = defineProps({
    field: {
        type: Object,
        default: {}
    },
    type: {
        type: Object,
        default: {}
    }
});

const entryTypes = ref([]);

const emitter = defineEmits(['change']);
const internalValue = ref({type: props.field.config.type || null, multi: props.field.config.multi || false});

watch(internalValue.value, (v) =>
{
    const config = cloneDeep(props.field.config);
    config.type = v.type;
    config.multi = v.multi;
    emitter('change', config);
});

const loadTypes = async () =>
{
    const types = await Entries.entryTypes(SailCMS.getLocales());

    for (let type of types) {
        entryTypes.value.push({value: type.handle, title: type.title});
    }
}

loadTypes();
</script>
