// src/components/fieldtypes/matrix.svelte
<script>
    import { _ } from 'svelte-i18n';
    import { Entries } from '@graphql/lib/entries.js';
    import { SailCMS } from '@graphql/index.js';
    import { Icon } from '@steeze-ui/svelte-icon';
    import { Menu, Trash } from '@steeze-ui/lucide-icons';
    import Sortable from 'sortablejs';
    import Searchable from '@components/utils/searchable.svelte';

    export let config = {fields: []};
    export let type = 'matrix';

    let internalValue = {fields: config.fields || []};
    let sortable = null;
    let selector = null;
    let isReady = false;
    let fieldList = [];
    let selectedField = null;

    const addField = () =>
    {
        internalValue.fields = [...internalValue.fields, selectedField];
        config = internalValue;
        selectedField = null;
        selector.clear();
    }

    const deleteField = (id) =>
    {
        let idx = internalValue.fields.findIndex(f => f === id);

        if (idx >= 0) {
            for (let field of fieldList) {
                if (field._id === id) {
                    field.used = false;
                }
            }

            internalValue.fields = internalValue.fields.filter((f, indx) => indx !== idx);
            config = internalValue;
            selector.updateFields(fieldList);
        }
    }

    const handleChange = () =>
    {
        let elms = document.getElementsByClassName('choice-item');
        let choices = [];

        for (let el of elms) {
            let id = el.getAttribute('data-id');
            let item = fieldList.find(f => f._id === id);
            choices = [...choices, item._id];
        }

        // Note: We do not update the internalValue here because it causes it reset the first time you move an item
        // This sets the right value at the top level and triggers all changes. The order of internalValue does not
        // matter at this point since the drag and drop library will tell us the order on every change.
        config.fields = choices;
    }

    const handleSelect = (e) =>
    {
        selectedField = e.detail

        for (let field of fieldList) {
            if (field._id === e.detail) {
                field.used = true;
            }
        }
    }

    const getField = (field) => fieldList.find(f => field === f._id);

    const init = async () =>
    {
        fieldList = await Entries.fields(SailCMS.getLocales());

        setTimeout(() => isReady = true, 25);

        const opts = {
            tag: 'div',
            direction: 'vertical',
            handle: '.list-dnd-handle',
            ghostClass: 'ghost',
            animation: 0,
            swapTreshold: 0.05,
            dragoverBubble: false,
            onEnd: handleChange
        };

        setTimeout(() =>
        {
            let el = document.querySelector('#choice-wrapper');
            sortable = new Sortable(el, opts);
        }, 50);
    }

    init();
</script>

{#if isReady}
    <div class="grid grid-cols-2 gap-y-6">
        <div class="w-full flex flex-row gap-x-4 items-center">
            <div class="flex-grow"><Searchable bind:this={selector} placeholder={$_('fields.options.add_field_ph')} showSelection={true} fields={fieldList} on:selected={handleSelect} /></div>
            <button on:click={addField} class="btn variant-filled-primary !py-[0.35rem]">{$_('system.add')}</button>
        </div>
        <div></div>

        <div id="choice-wrapper" class="choice-wrapper">
            {#each internalValue.fields as field, idx}
                {@const f = getField(field)}
                <div class="choice-item group" data-id={f._id}>
                    <div class="flex flex-row gap-x-4 items-center">
                        <div class="cursor-grab list-dnd-handle">
                            <Icon src={Menu} size="24"/>
                        </div>
                        <span>{f.name}</span>
                    </div>
                    <div class="flex-col items-center hidden group-hover:flex">
                        <button on:click={() => deleteField(f._id)} class="hover:text-red-500">
                            <Icon src={Trash} size="20" />
                        </button>
                    </div>
                </div>
            {:else}
                <h2 class="text-center text-lg text-surface-400 dark:text-surface-400">{$_('fields.options.no_fields')}</h2>
            {/each}
        </div>
    </div>
{/if}

<style lang="scss">
    .choice-wrapper {
        @apply border border-surface-300 dark:border-surface-400 p-4 rounded-md flex flex-col gap-y-4;
    }

    .choice-item {
        @apply flex flex-row justify-between items-center border border-surface-300;
        @apply dark:border-surface-400 p-4 hover:border-surface-500 dark:hover:border-surface-200;
        @apply dark:bg-surface-700;
    }

    .ghost {
        opacity: 0.55;
    }
</style>

// src/components/entries/fields/types/Matrix.vue
<template>
    <div class="tw-w-full tw-grid tw-grid-cols-1 md:tw-grid-cols-2 tw-gap-y-4 tw-gap-x-6 tw-mt-4">
        <div class="tw-w-full tw-col-span-2">
            <div class="tw-flex tw-flex-col md:tw-flex-row tw-items-start tw-w-full md:tw-w-8/12 lg:tw-w-7/12 xl:tw-w-6/12 tw-gap-x-6">
                <v-select
                    v-model="selectedField"
                    :items="fieldList"
                    id="type-selector"
                    :label="$t('fields.options.field')"
                    color="primary"
                    variant="outlined"
                    density="comfortable"
                    placeholder="Type"
                    :hide-details="true"
                    :persistent-hint="false"
                    class="tw-col-span-2"
                ></v-select>
                <div class="tw-flex-grow tw-w-4/12">
                    <v-btn @click.prevent="addChoice" variant="flat" color="primary" class="tw-mt-1.5">{{ $t('fields.options.add_field') }}</v-btn>
                </div>
            </div>

            <div v-if="showAlreadySelected" class="tw-mt-6 tw-p-3 tw-border tw-border-red-500 tw-w-6/12 tw-rounded-lg tw-text-red-500 tw-flex tw-items-center tw-gap-x-2">
                <v-icon icon="mdi-alert-outline"/>
                {{ $t('fields.matrix_error') }}
            </div>

            <div
                class="tw-border tw-p-4 tw-mt-6 tw-mb-2 tw-w-full md:tw-w-8/12 lg:tw-w-7/12 xl:tw-w-6/12 tw-rounded-md"
                :class="{'tw-border-black/30': $vuetify.theme.name === 'light', 'tw-border-white/30': $vuetify.theme.name === 'dark'}"
            >
                <h3 v-if="internalValue.fields.length === 0" class="tw-text-center tw-font-medium">{{ $t('fields.options.no_fields') }}</h3>

                <div v-else id="sortable-choices" class="tw-flex tw-flex-col tw-gap-y-2">
                    <div
                        v-for="choice in internalValue.fields"
                        :id="choice.value"
                        class="tw-px-4 tw-py-2 tw-group tw-rounded-md tw-flex tw-flex-row tw-items-center tw-justify-between"
                        :class="{'hover:tw-bg-neutral-800 tw-border tw-border-white/30': $vuetify.theme.name === 'dark', 'hover:tw-bg-gray-300 tw-border tw-border-black/30': $vuetify.theme.name === 'light'}"
                    >
                        <div>
                            <v-icon icon="mdi-menu" class="list-dnd-handle tw-mr-1 tw-cursor-grab"/>
                            {{ choice.title }}
                        </div>
                        <a href="" @click.prevent="removeSelection(choice)" class="hover:tw-text-red-500 tw-invisible group-hover:tw-visible">
                            <v-icon icon="mdi-trash-can-outline" size="small"/>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</template>

<script setup>
import { watch, ref, onMounted, nextTick, onBeforeMount } from 'vue';
import { cloneDeep } from 'lodash';
import { useI18n } from 'vue-i18n';
import Sortable from 'sortablejs';
import { Entries } from '@/libs/graphql/lib/entries';
import { availableTypes } from '@/libs/fieldTypes';
import { SailCMS } from '@/libs/graphql';

const i18n = useI18n();

const rules = {
    required: value => !!value || i18n.t('user.errors.required'),
};

const props = defineProps({
    field: {
        type: Object,
        default: {}
    },
    type: {
        type: Object,
        default: {}
    }
});

const showAlreadySelected = ref(false);
const fieldList = ref([]);
const selectedField = ref(null);

const addChoice = () =>
{
    let item = fieldList.value.find(f => f.value === selectedField.value);

    if (item.disabled) {
        showAlreadySelected.value = true;
        return;
    } else {
        showAlreadySelected.value = false;
    }

    item.disabled = true;
    internalValue.value.fields.push(item);
    selectedField.value = null;

    nextTick(() =>
    {
        if (internalValue.value.fields.length > 0 && !sortableCreated.value) {
            sortableCreated.value = true;
            let el = document.querySelector('#sortable-choices');
            sortable = new Sortable(el, opts);
        }
    });
}

const removeSelection = (item) =>
{
    document.getElementById(item.value).remove();
    handleChange(null);

    // Update listing to allow that field again
    for (let field of fieldList.value) {
        if (field.value === item.value) {
            field.disabled = false;
        }
    }
}

const handleChange = (e) =>
{
    let choices = [];
    let children = Array.from(document.querySelector('#sortable-choices').children);

    for (let child of children) {
        const item = internalValue.value.fields.find(i => i.value === child.id);

        if (item) {
            choices.push(item);
        }
    }

    choiceList = choices;
    const config = cloneDeep(props.field.config);
    config.fields = choices.map(c =>
    {
        return c.value;
    });

    emitter('change', config);
}

const emitter = defineEmits(['change']);
const internalValue = ref({fields: props.field.config.fields || []});
let choiceList = [];

let sortable = null;
const label = ref('');
const value = ref('');
const sortableCreated = ref(false);

const opts = {
    tag: 'div',
    direction: 'vertical',
    handle: '.list-dnd-handle',
    ghostClass: 'ghost',
    animation: 0,
    swapTreshold: 0.05,
    dragoverBubble: false,
    onEnd: handleChange
};

onMounted(() =>
{
    if (internalValue.value.fields.length > 0) {
        sortableCreated.value = true;
        let el = document.querySelector('#sortable-choices');
        sortable = new Sortable(el, opts);
    }
});

onBeforeMount(async () =>
{
    let fields = await Entries.fields(SailCMS.getLocales());

    fieldList.value = fields.map(field => {
        return {value: field.key, title: field.name, disabled: false}
    });
});
</script>

<style>
.ghost {
    opacity: 0.5;
}
</style>
